# Builder stage
FROM golang:1.19-alpine as builder


# Install make
RUN apk update && apk add make

# Copy the source code from the host to the container
COPY pkg /workdir/app/pkg
COPY tools /workdir/app/tools
COPY staging /workdir/app/staging
COPY cmd /workdir/app/cmd
COPY vendor /workdir/app/vendor
COPY go.mod /workdir/app/go.mod
COPY go.sum /workdir/app/go.sum
COPY Makefile /workdir/app/Makefile

WORKDIR /workdir/app

RUN make maroonedpods_operator
RUN make csv-generator

# Final stage
FROM golang:1.19-alpine


# Copy the binary from the builder stage to the final image
COPY --from=builder /workdir/app/maroonedpods_operator /app/maroonedpods_operator
COPY --from=builder /workdir/app/bin/csv-generator /usr/bin/csv-generator

# Set the working directory to /app
WORKDIR /app

RUN adduser -u 1001 -D -s /bin/sh -h /app/maroonedpods_operator maroonedpods_operator
USER 1001

# Set the entrypoint to the binary
ENTRYPOINT ["/app/maroonedpods_operator"]
